apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemo-fs-api-deployment
  #namespace: dockerdemo
spec:
  selector:
    matchLabels:
      app: dockerdemo-fs-api
  replicas: 2
  template:
    metadata:
      labels:
        app: dockerdemo-fs-api
    spec:
      containers:
        - name: dockerdemo-fs-api-container
          image: 10.10.101.141:37002/dockerdemo_fs_api
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemo-fs-web-deployment
  #namespace: dockerdemo
spec:
  selector:
    matchLabels:
      app: dockerdemo-fs-web
  replicas: 2
  template:
    metadata:
      labels:
        app: dockerdemo-fs-web
    spec:
      containers:
        - name: dockerdemo-fs-web-container
          image: 10.10.101.141:37002/dockerdemo_fs_web
          ports:
            - containerPort: 80