apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerdemo-fs-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dockerdemo-fs-api
    spec:
      containers:
        - name: dockerdemo-fs-api-container
          image: 10.10.101.22:28080/dockerdemo-fs-api
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerdemo-fs-web-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dockerdemo-fs-web
    spec:
      containers:
        - name: dockerdemo-fs-web-container
          image: 10.10.101.22:28080/dockerdemo-fs-web
          ports:
            - containerport: 80