apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dockerdemo-ingress
  namespace: dockerdemo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: defsapi.demo.com
      http:
        paths:
          - backend:
              serviceName: dockerdemo-fs-api-service
              servicePort: 80
    - host: defsweb.demo.com
      http:
        paths:
          - backend:
              serviceName: dockerdemo-fs-web-service
              servicePort: 80
    - host: redis.demo.com
      http:
        paths:
          - backend:
              serviceName: dockerdemo-redis-service
              servicePort: 6379