apiVersion: v1
kind: Service
metadata:
  name: dockerdemo-fs-api-service
spec:
  type: NodePort
  selector:
    app: dockerdemo-fs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32001
---
apiVersion: v1
kind: Service
metadata:
  name: dockerdemo-fs-web-service
spec:
  type: NodePort
  selector:
    app: dockerdemo-fs-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32002
---
apiVersion: v1
kind: Service
metadata:
  name: dockerdemo-redis-service
spec:
  type: NodePort
  selector:
    app: dockerdemo-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 32003